/* Generated By:JavaCC: Do not edit this line. ParseSalaConstants.java */
package unioeste.ia.trabalho1.controle.parser.sala;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParseSalaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LETRA = 7;
  /** RegularExpression Id. */
  int SIMBOLO = 8;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 9;
  /** RegularExpression Id. */
  int SERIE = 10;
  /** RegularExpression Id. */
  int CONSTANTE = 11;
  /** RegularExpression Id. */
  int DIGIT = 12;
  /** RegularExpression Id. */
  int ESPACO = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<LETRA>",
    "<SIMBOLO>",
    "<IDENTIFICADOR>",
    "<SERIE>",
    "<CONSTANTE>",
    "<DIGIT>",
    "<ESPACO>",
    "\", \"",
    "\".\"",
  };

}
