/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JanPrinc.java
 *
 * Created on 26/05/2010, 18:36:31
 */

package gui;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import unioeste.ia.trabalho1.controle.facade.impl.FacadeImpl;
import unioeste.ia.trabalho1.controle.parser.centro.ParseCursos;
import unioeste.ia.trabalho1.controle.parser.sala.ParseSala;
import unioeste.ia.trabalho1.pojo.*;

/**
 *
 * @author Luiz
 */
public class JanPrinc extends javax.swing.JFrame {

    private List<Curso> cursos;

    private List<Serie> series;

    private List<Disciplina> disciplinas;

    private List<Professor> professores;

    private List<Sala> salas;
    /** Creates new form JanPrinc */
    public JanPrinc() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTipoAlg = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        botAbrirCursos = new javax.swing.JButton();
        botAbrirSalas = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        botUtilSerie = new javax.swing.JRadioButton();
        botUtilDisc = new javax.swing.JRadioButton();
        botFazHC = new javax.swing.JButton();
        botFazProf = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        selecaoCurso = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        selecaoSalas = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        selecaoProf = new javax.swing.JComboBox();
        botVisualizar = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        painelSalas = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Arquivos"));

        botAbrirCursos.setText("Abrir arquivo de cursos");
        botAbrirCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAbrirCursosActionPerformed(evt);
            }
        });

        botAbrirSalas.setText("Abir arquivo de salas");
        botAbrirSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAbrirSalasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botAbrirCursos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(botAbrirSalas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(botAbrirCursos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botAbrirSalas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Algoritmos"));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Utilizar"));

        grupoTipoAlg.add(botUtilSerie);
        botUtilSerie.setSelected(true);
        botUtilSerie.setText("Matriculados pro série");

        grupoTipoAlg.add(botUtilDisc);
        botUtilDisc.setText("Matriculados na disciplina");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botUtilSerie)
                    .addComponent(botUtilDisc))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(botUtilSerie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botUtilDisc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botFazHC.setText("Gulosa");
        botFazHC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botFazHCActionPerformed(evt);
            }
        });

        botFazProf.setText("Profundidade");
        botFazProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botFazProfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(botFazHC, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(botFazProf, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botFazHC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botFazProf)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Opções"));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Curso"));

        selecaoCurso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selecaoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(selecaoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Salas"));

        selecaoSalas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selecaoSalas, 0, 78, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(selecaoSalas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Professor"));

        selecaoProf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos" }));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selecaoProf, 0, 78, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(selecaoProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botVisualizar.setText("Visualizar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botVisualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(botVisualizar)))
                .addContainerGap(5, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Salas e horários"));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelSalas, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(painelSalas, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, 0, 90, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public ArrayList<String> converteCursos()
    {
        ArrayList<String> c = new ArrayList<String>();
        c.add("Todos");
        for (Curso a : cursos)
        {
            c.add(a.getNmCurso());
        }
        return c;
    }

    public ArrayList<String> converteSalas()
    {
        ArrayList<String> c = new ArrayList<String>();
        c.add("Todos");
        for (Sala a : salas)
        {
            c.add(a.getNmSala());
        }
        return c;
    }

    public ArrayList<String> converteProfessor()
    {
        ArrayList<String> c = new ArrayList<String>();
        c.add("Todos");
        for (Professor a : professores)
        {
            c.add(a.getNm_professor());
        }
        return c;
    }

    private void botAbrirCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAbrirCursosActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser(".");
        if (file.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
        {
            try {
                ParseCursos p = new ParseCursos(new FileReader(file.getSelectedFile()));
                p.load();
                disciplinas = p.getListaDisciplina();
                cursos = p.getListaCurso();
                series = p.getListaSerie();
                professores = p.getListaProfessor();
                selecaoCurso.setModel(new DefaultComboBoxModel(converteCursos().toArray()));
                selecaoProf.setModel(new DefaultComboBoxModel(converteProfessor().toArray()));
                JOptionPane.showMessageDialog(this, "Arquivo aberto com sucesso.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_botAbrirCursosActionPerformed

    private void botAbrirSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAbrirSalasActionPerformed
        JFileChooser file = new JFileChooser(".");
        if (file.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
        {
            try {
                ParseSala p = new ParseSala(new FileReader(file.getSelectedFile()));
                p.load();
                salas = p.getListaSala();
                selecaoSalas.setModel(new DefaultComboBoxModel(converteSalas().toArray()));
                JOptionPane.showMessageDialog(this, "Arquivo aberto com sucesso.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_botAbrirSalasActionPerformed

    private void botFazHCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botFazHCActionPerformed
        if (botUtilSerie.isSelected())
        {
            FacadeImpl alocador = new FacadeImpl();
            alocador.gerarGreedySerie(cursos, disciplinas, series, salas, professores);
            String[] diaSemana = {"Segunda", "Terça", "Quarta", "Quinta", "Sexta"};
            List<Sala> alocacoes = alocador.getListaSala();
            painelSalas.removeAll();
            for (Sala sala : alocacoes)
            {
                String[][] aulas = alocador.gerarMatriz(sala, 5, 11);
                painelSalas.addTab(sala.getNmSala(), new JTable(new DefaultTableModel(aulas, diaSemana)));
            }
        }
        else
        {
            FacadeImpl alocador = new FacadeImpl();
            alocador.gerarGreedySerie(cursos, disciplinas, series, salas, professores);
            String[] diaSemana = {"Segunda", "Terça", "Quarta", "Quinta", "Sexta"};
            List<Sala> alocacoes = alocador.getListaSala();
            painelSalas.removeAll();
            for (Sala sala : alocacoes)
            {
                String[][] aulas = alocador.gerarMatriz(sala, 5, 11);
                painelSalas.addTab(sala.getNmSala(), new JTable(new DefaultTableModel(aulas, diaSemana)));
            }
        }
    }//GEN-LAST:event_botFazHCActionPerformed

    private void botFazProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botFazProfActionPerformed
        if (botUtilSerie.isSelected())
        {
            FacadeImpl alocador = new FacadeImpl();
            alocador.gerarProfundidadeSeries(cursos, disciplinas, series, salas, professores);
            String[] diaSemana = {"Segunda", "Terça", "Quarta", "Quinta", "Sexta"};
            List<Sala> alocacoes = alocador.getListaSala();
            painelSalas.removeAll();
            for (Sala sala : alocacoes)
            {
                String[][] aulas = alocador.gerarMatriz(sala, 5, 11);
                painelSalas.addTab(sala.getNmSala(), new JTable(new DefaultTableModel(aulas, diaSemana)));
            }
        }
        else
        {
            FacadeImpl alocador = new FacadeImpl();
            alocador.gerarProfundidadeDisciplina(cursos, disciplinas, series, salas, professores);
            String[] diaSemana = {"Segunda", "Terça", "Quarta", "Quinta", "Sexta"};
            List<Sala> alocacoes = alocador.getListaSala();
            painelSalas.removeAll();
            for (Sala sala : alocacoes)
            {
                String[][] aulas = alocador.gerarMatriz(sala, 5, 11);
                painelSalas.addTab(sala.getNmSala(), new JTable(new DefaultTableModel(aulas, diaSemana)));
            }
        }
    }//GEN-LAST:event_botFazProfActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanPrinc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botAbrirCursos;
    private javax.swing.JButton botAbrirSalas;
    private javax.swing.JButton botFazHC;
    private javax.swing.JButton botFazProf;
    private javax.swing.JRadioButton botUtilDisc;
    private javax.swing.JRadioButton botUtilSerie;
    private javax.swing.JButton botVisualizar;
    private javax.swing.ButtonGroup grupoTipoAlg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane painelSalas;
    private javax.swing.JComboBox selecaoCurso;
    private javax.swing.JComboBox selecaoProf;
    private javax.swing.JComboBox selecaoSalas;
    // End of variables declaration//GEN-END:variables

}
